include:
  - path: ./cloudflared/docker-compose.yml
  - path: ./n8n/docker-compose.yml
  - path: ./glances/docker-compose.yml
  - path: ./open-webui/docker-compose.yml
  - path: ./vaultwarden/docker-compose.yml
  - path: ./uptime-kuma/docker-compose.yml
  - path: ./trafilatura/docker-compose.yml
  - path: ./crawl4ai/docker-compose.yml
